name: tienda_online
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Base de datos local con Drift
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Backend con Supabase
  supabase_flutter: ^2.0.0
  
  # Utilitarios
  uuid: ^4.1.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  
  # UI y estado
  provider: ^6.1.1
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Autenticación y seguridad
  crypto: ^3.0.3
  
  # Validaciones
  formz: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  assets: 
    - .env
